OUTFIT_QUERIES = [
    # occasion-based
    "outfit for a beach wedding this summer",
    "what should I wear to a job interview",
    "I need a business casual look for the office",
    "put together something for a first date",
    "outfit for a summer music festival",
    "what to wear to a cocktail party",
    "I need clothes for a hiking trip",
    "dress me for a formal dinner",
    "outfit for a casual Friday at work",
    "what to wear to brunch with friends",
    "I need an outfit for my graduation ceremony",
    "help me style something for a garden party",
    "going to a wedding next weekend need an outfit",
    "coordinate an outfit for a night out",
    "I need clothes for a winter ski trip",
    # activity-based
    "what to wear for a yoga class",
    "need running clothes for marathon training",
    "outfit for the gym that looks good",
    "going camping this weekend need clothes",
    "tennis outfit for a tournament",
    "cycling gear for long distance riding",
    # lifestyle-based
    "something warm and cozy for staying home",
    "comfortable loungewear for working from home",
    "casual everyday outfit for running errands",
    "travel outfit that is comfortable for a long flight",
    "back to school outfit for my daughter",
    "outfit for a toddler birthday party",
    "cute outfit for my teenage son",
    "athleisure look for weekend errands",
    # vague multi-item
    "I want to look stylish this fall",
    "help me build a capsule wardrobe",
    "need a whole new summer wardrobe",
    "I want to dress better at work",
    "put together a preppy look",
    "streetwear outfit with sneakers",
    "boho chic look for vacation",
    "minimalist outfit all black everything",
    "need to update my wardrobe for spring",
    "smart casual look for a date night",
]

SINGLE_ITEM_QUERIES = [
    # specific product searches
    "I need a turkey necklace with enamel design",
    "looking for comfortable thick cotton socks",
    "I want to buy a Casio digital sport watch",
    "need a wireless bra with good support",
    "looking for a hat that fits a big head",
    "I need a trucker hat with LED lights",
    "want to find over the calf tube socks",
    "looking for a moissanite pendant necklace",
    "I need a lightweight quarter zip fleece pullover",
    "comfortable shorts with built-in compression liner",
    # product-type specific
    "waterproof hiking boots for men",
    "gold hoop earrings for women",
    "leather bifold wallet with RFID blocking",
    "polarized aviator sunglasses",
    "silk tie with paisley pattern",
    "stainless steel water bottle",
    "memory foam house slippers",
    "wool beanie hat for winter",
    "compression socks for nurses",
    "crossbody bag with phone pocket",
    "sundress",
    "sun dress",
    "maxi dress",
    # brand-specific
    "Nike running shoes for flat feet",
    "Adidas golf pants slim fit",
    "Ray-Ban wayfarer sunglasses",
    "Levi's 501 original fit jeans",
    "Under Armour polo shirt moisture wicking",
    # attribute-focused
    "red dress for a party",
    "black leather belt with silver buckle",
    "warm sherpa lined hoodie",
    "ankle boots with side zipper",
    "oversized flannel shirt for women",
    # review-like (C4 style)
    "I need socks that stay up and don't slide down",
    "looking for a bra that doesn't dig into shoulders",
    "want a watch that is easy to read in the dark",
    "need a hat with adjustable strap for large head",
    "looking for earrings that come as a pair not singles",
    "I want a bag that fits my 15 inch laptop",
    "need gloves that work with touchscreens",
    "looking for a scarf that is warm but not bulky",
    "want shoes with good arch support for plantar fasciitis",
    "I need a belt that fits waist sizes 36 to 40",
]
